sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t sbyoung25/docker-react . 
  
script:
  - docker run -e CI=true sbyoung25/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sbyoung25-docker-react"
  env: "Sbyoung25dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-076657815191"
  bucket_path: "sbyoung25-docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
